<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Low Stock Alert</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
            background-color: #f8f9fa;
            margin: 0;
            padding: 20px;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
            background-color: #ffffff;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
            overflow: hidden;
        }
        .header {
            background-color: #dc3545;
            color: #ffffff;
            padding: 20px;
            text-align: center;
        }
        .content {
            padding: 30px;
        }
        .alert-icon {
            font-size: 48px;
            color: #dc3545;
            text-align: center;
            margin-bottom: 20px;
        }
        .product-info {
            background-color: #f8f9fa;
            border-left: 4px solid #dc3545;
            padding: 15px;
            margin: 20px 0;
        }
        .footer {
            background-color: #f8f9fa;
            padding: 20px;
            text-align: center;
            font-size: 14px;
            color: #6c757d;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🚨 Low Stock Alert</h1>
        </div>
        
        <div class="content">
            <div class="alert-icon">⚠️</div>
            
            <h2>Immediate Attention Required</h2>
            
            <p>Hello Admin,</p>
            
            <p>A product in your inventory is running critically low on stock and requires immediate attention.</p>
            
            <div class="product-info">
                <h3>Product Details:</h3>
                <p><strong>Product Name:</strong> {{ $product->name }}</p>
                <p><strong>SKU:</strong> {{ $product->sku }}</p>
                <p><strong>Current Stock:</strong> <span style="color: #dc3545; font-weight: bold;">{{ $product->stock_quantity }} units</span></p>
                <p><strong>Price:</strong> ${{ number_format($product->price, 2) }}</p>
            </div>
            
            <p>This low stock alert was triggered after a recent order was processed. Please consider restocking this product to avoid stockouts.</p>
            
        </div>
        
        <div class="footer">
            <p>This notification was automatically generated by your E-commerce System.</p>
            <p>Time: {{ now()->format('F j, Y g:i A') }}</p>
        </div>
    </div>
</body>
</html>